version: "3.9"
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
  jwt:
    build: .
    ports:
      - "8000:8000"
    restart: always
    environment:
      PG_HOST: "postgres"
      PG_PORT: "5432"
      PG_USER: "postgres"
      PG_PASS: "password"
      PG_DBNAME: "postgres"
      PORT: "8000"
      JWT_SECRET_KEY: "asdf1234"
    depends_on:
      - postgres