version: "3.9"
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
  api:
    image: nillga/api-gateway
    restart: always
    ports:
      - "1323:1323"
    environment:
      USERS_HOST: "http://jwt:8000"
      MEHMS_HOST: "http://mehms:8080"
      PORT: "8080"
      SWAG: ":1323"
      JWT_SECRET_KEY: "asdf1234"
    depends_on:
      - jwt
  gateway:
    image: nillga/frontend-gateway
    restart: always
    environment:
      USERS_HOST: "http://jwt:8000"
      MEHMS_HOST: "http://mehms:8080"
      PORT: ":8080"
      SWAG: ":1323"
      JWT_SECRET_KEY: "asdf1234"
    depends_on:
      - jwt

  jwt:
    image: nillga/users
    restart: always
    environment:
      PG_HOST: "postgres"
      PG_PORT: "5432"
      PG_USER: "postgres"
      PG_PASS: "password"
      PG_DBNAME: "postgres"
      PORT: "8000"
      JWT_SECRET_KEY: "asdf1234"
    depends_on:
      - mehms
  mehms:
    image: nillga/mehms
    restart: always
    environment:
      PG_HOST: "postgres"
      PG_PORT: "5432"
      PG_USER: "postgres"
      PG_PASS: "password"
      PG_DBNAME: "postgres"
    depends_on:
      - postgres
  frontend:
    image: nillga/frontend
    restart: always
    ports:
      - "42069:80"
    depends_on:
      - gate-prox
  gate-prox:
    image: nillga/gateway
    restart: always
    ports:
      - "420:80"
    depends_on:
      - gateway